# Generated by Django 4.2.7 on 2023-12-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='att_full_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_full_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutorial_full_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
